int print(string str);
int println(string str) { 
    return print(str + "\n");
}

println(fib1(7) + "");
println(fib2(8) + "");

int fib1(int n) {

    if(n == 1 || n == 2) {
        return 1;
    }

    int a = 1;
    int b = 1;
    int i;
    int t;
    for(i = 0; i < n - 2; i ++) {
        t = a + b;
        a = b;
        b = t;
    }

    return b;
}

int fib2(int n) {
    if(n <= 0) {
        return 0;
    }   
    if(n == 1 || n == 2) {
        return 1;
    }

    return fib2(n - 1) + fib2(n - 2);
}

int max(int a, int b) {
    if(a >= b) {
        return a;
    }
    return b;
}

int gcd(int a, int b) {
    if(b == 0) {
        return a;
    }

    return gcd(b, a % b);
}

int x = 10;
int y = 123;
println(max(x, y) + "");  //123
println(gcd(9, 18) + ""); //9
println(gcd(9, 21) + ""); //3